/** Mixed North + South weeknight kitchen so both regions can match. */
export const DEMO_PANTRY_SLUGS = [
  "rice",
  "toor-dal",
  "moong-dal",
  "chickpeas",
  "onion",
  "tomato",
  "potato",
  "spinach",
  "cabbage",
  "ginger",
  "garlic",
  "green-chili",
  "curry-leaves",
  "cilantro",
  "lemon",
  "cumin",
  "mustard-seeds",
  "turmeric",
  "chili-powder",
  "coriander-powder",
  "garam-masala",
  "sambar-powder",
  "rasam-powder",
  "pepper",
  "yogurt",
  "paneer",
  "coconut",
  "tamarind",
  "eggs",
  "oil",
  "salt",
  "ghee",
] as const;

export const DEMO_PANTRY_SET = new Set<string>(DEMO_PANTRY_SLUGS);
